### ISSUE TITLE
empty string passed to getElementById()

### ISSUE THREAD

**Issue by mastacheata** [PA-Platform/RESTClient-APS#27]
Hello,
I always see this error in the console when trying to work with the authentication menu:
"empty string passed to getElementById()" in jQuery.js:164

Is this related to the extension itself or could this be a conflict with another extension I installed?

**Comment by gear54rus** [comment]
This is from old jQuery (version 1.x was inherited from RESTClient). I will look into that, but it's not really a big problem per se.

**Comment by gear54rus** [comment]
Need to research the possibility of upgrading jQuery and other libs.

**Comment by mastacheata** [comment]
I'm not really sure if that's what causes my problems with both your and the original extension, but neither works as expected anymore.
The whole OAuth part is broken. I can open the dialog, but can't insert any of the generated (if it generates anything at all) headers/query string parameters into my request.
The insert button(s) don't do anything at all.

**Comment by gear54rus** [comment]
Please clarify what do you mean by `original extension`. If by that, you mean simple RESTClient, then [they cause conflicts when installed together](https://github.com/PA-Platform/RESTClient-APS/wiki/Frequently-Asked-Questions#can-i-have-both-restclient-and-restclient-aps-installed-at-the-same-time). Please [remove them both and their data](https://github.com/PA-Platform/RESTClient-APS/wiki/Frequently-Asked-Questions#how-do-i-clear-settings-and-persistent-data-for-this-extension) and then re-install RESTClient APS.

**Comment by mastacheata** [comment]
I meant the source of this fork. And no, I don't have them installed at the same time.

**Comment by gear54rus** [comment]
We've determined that the original reported problem is a bug, let's move the discussion to new issue.

**Comment by mastacheata** [comment]
I mentioned my problem here, because I thought that missing Element might be the root cause for my problems.
I'm a web developer by trade (PHP & ExtJS), but have no experience at all with extensions.
To me it looks like this extension is basically just JavaScript code and thus an element that can't be found is usually a pretty bad issue causing all kinds of weird problems.

Not sure if I understand you correctly. Did you determine the two issues are not connected or did you split the "problem" part from the "technical bug" just for organizational reasons?

**Comment by gear54rus** [comment]
https://github.com/twbs/bootstrap/issues/10044

This is the one.

https://github.com/bgaillard/bootstrap/commit/3a058ee698ef2a4b00625868b044e6e2d7a59db4

https://github.com/twbs/bootstrap/commit/22f9767714a9f80d5d12479725e8875bdd83f341

Will use fix from the former.
