### ISSUE TITLE
OAuth window does not work

### ISSUE THREAD

**Issue by gear54rus** [PA-Platform/RESTClient-APS#28]
A problem was reported in #27:

I'm not really sure if that's what causes my problems with both your and the original extension, but neither works as expected anymore.
The whole OAuth part is broken. I can open the dialog, but can't insert any of the generated (if it generates anything at all) headers/query string parameters into my request.
The insert button(s) don't do anything at all.

**Comment by gear54rus** [comment]
@mastacheata, can you please tell me if a [complete wipe](https://github.com/PA-Platform/RESTClient-APS/wiki/Frequently-Asked-Questions#how-do-i-clear-settings-and-persistent-data-for-this-extension) solves the issue? Can I somehow get access to your machine (I can setup WebEx session) to debug it?

**Comment by mastacheata** [comment]
Complete wipe does NOT resolve the issue.
We're using TeamViewer over here for remote hands on with clients, but I'd be willing to install another software if you tell me which version I need (I've had bad experience with incompatible versions of remote control software in the past, so forgive me if that might sound stupid)

I'm a web developer by trade, but I've got no experience at all with developing or debugging extensions. I really liked the original version, but their developer is no longer maintaining the software, so I just hoped you had some more experience and could easily help out here.

**Comment by gear54rus** [comment]
> Not sure if I understand you correctly. Did you determine the two issues are not connected or did you split the "problem" part from the "technical bug" just for organizational reasons?

I've determined that by the fact that it also prints those damn messages when operating normally :)

During the next 12 hours I'll research on OAuth part a bit and try to figure out why it might not be working. Also, during this time we can set up a remote session (although by your comments I feel like out timezones are a bit incompatible). Please mention me like this: @mastacheata in this thread when you can attend the session.

**Comment by mastacheata** [comment]
@gear54rus I don't think we're that much incompatible. I'm just a "night-owl" and tend to write on github when it's already very late.
If the location you mentioned in your profile is correct, you're 4 hours ahead of me 
I'm around for the next 4 hours or so today, or if you'd like to try at an earlier time of the day, I could make anything between 10 am and 2 pm tomorrow.

**Comment by gear54rus** [comment]
@mastacheata Can we start in 30 minutes from now?

**Comment by mastacheata** [comment]
@gear54rus Sure. I'll be around

**Comment by gear54rus** [comment]
@mastacheata please use this URL to join (webex software will be downloaded) https://parallels.webex.com/join/support4

**Comment by gear54rus** [comment]
During webex we found out that HTML UI that OAuth1 uses is disconnected from JS that is written for it...

**Comment by mastacheata** [comment]
I found and resolved all OAuth related problems.

Mostly  changed what we found during the webex session (buttons not correctly mapped to events), but also found that the OAuth1 generator tried to URLEncode the special characters in the OAuth1 signature, which inevitably leads to bad signatures that won't work.
The OAuth2 Generator works almost immediately (there were 2 or 3 occurences of #window-oauth2 where it must actually be #modal-oauth2

Before I send in a pull-request, I have to ask if you would be open to me running a reformat on all the JS code in this project.
The indentation is awful and makes it almost unreadable.

If not, I'll make a pull-request ready over the weekend that fits the original coding style (i.e. none at all).

I also did some changes to the HTML (mostly adding IDs to the inputs to properly associate the corresponding labels)

**Comment by gear54rus** [comment]
That's cool, thanks for the contribution!

>  I have to ask if you would be open to me running a reformat on all the JS code in this project.

I had to deal with that as well. Opted to not-reformat the whole files, but instead [format my own code](http://jsbeautifier.org/) (**2 spaces**, defaults otherwise) where possible before committing.

**Comment by mastacheata** [comment]
Run changes through beautifier, 2 spaces, rest default.
Is that summarized correctly?

I'll try to get a patch ready over the weekend, might be monday before I have that, though (Pentecost-monday is a public holiday here in Germany).

**Comment by gear54rus** [comment]
Yes, pretty much. It's not a problem, I'll format it after accepting if needed. Happy Holidays :)

**Comment by gear54rus** [comment]
@mastacheata Hello, any word on that pull request?:)

**Comment by mastacheata** [comment]
Sorry for the delay. I'm still figuring out how to pick only the actual changes. Should be done in an hour or so.

**Comment by mastacheata** [comment]
@gear54rus See #30

**Comment by gear54rus** [comment]
Fixed in #30.
